### ISSUE TITLE
[sysinfo] 5G shows up as 4G

### ISSUE THREAD

**Issue by Aqqly** [mugman174/vendetta-plugins#5]
Hi,

Just a little thing, when you're connected to a 5G network and you do /sysinfo it shows up as 4G.

Also a little suggestion that I'd like to see is that the command would also show how much plugins are installed for AliucordRN, just as the default /debug command shows.

**Comment by mugman174** [comment]
Unfortunately, the cellular indicator is not under my control. It utilizes a module built into the Discord app to fetch the cellular information, and I can't really control that module, so I can't detect 5G from 4G unless that module implements that.

However, I could add a counter for the amount of plugins installed. I'll add that to my todo list.
